steps:
  # Step 1: Trigger the OpenShift build
  - label: "Trigger OpenShift Build"
    commands:
      - echo "Triggering OpenShift build"
      - |
        # Start the build using oc start-build
        oc start-build vllm-main-buildconfig-2 --wait

  # Step 2: Wait for the OpenShift build to complete
  - label: "Wait for Build to Finish"
    commands:
      - echo "Waiting for OpenShift build to finish"
      - |
        # Wait until the build completes
        oc wait --for=condition=complete build/vllm-main-buildconfig-2-4 --timeout=120m
