steps:
  - label: "Run on default Agent"
    key: delay
    commands: 
      - echo Running on default queue
      - sleep 16

  - label: "Run on queue1 Agent"
    depends_on: delay
    command: "echo Running on queue1"
    agents:
      queue: "queue1"

  - label: "Run on queue2 Agent"
    command: "echo Running on queue2"
    agents:
      queue: "queue2"

  - label: "Run on oc-image Agent"
    commands: 
      - echo Running on ocimage
      - oc whoami
      - "oc patch configmap agent-stack-k8s-config-test --type=json -p='[{"op": "replace", "path": "/data/config.yaml", "value": "agent-token-secret: agent-stack-k8s-secrets\nnamespace: buildkite\ncluster-uuid: 2ec33b8f-cb1b-4bb0-bdf8-d0f44ec6ea2b\ndebug: false\ndefault-checkout-params:\n envFrom:\n - configMapRef:\n name: agent-stack-k8s-env-vars-config\ndefault-command-params:\n envFrom:\n - configMapRef:\n name: agent-stack-k8s-env-vars-config\nimage: quay.io/tsalawu0/buildkite-runner:latest\nimage-pull-backoff-grace-period: 60s\njob-ttl: 5m\nmax-in-flight: 100\norg: test-org2-5\npod-spec-patch:\n containers:\n - name: agent\n - name: checkout\n - name: container-0\n initContainers:\n - name: copy-agent\npoll-interval: 5s\nprohibit-kubernetes-plugin: true\ntags:\n- queue=oc-image\n- priority=high"}]'"
    agents:
      queue: "oc-image"
