steps:
  - label: "Build Docker Image with Kaniko"
    # image: gcr.io/kaniko-project/executor:latest  # Use Kaniko executor image
    env:
      DOCKER_CONFIG: /workspace/.docker  # Set the Docker config path for Kaniko
    command:
      - mkdir -p /workspace/.docker  # Create directory for Docker config
      - echo "{\"auths\":{\"${QUAY_REGISTRY}\":{\"username\":\"${QUAY_USERNAME}\",\"password\":\"${QUAY_PASSWORD}\"}}}" > /workspace/.docker/config.json
      - /kaniko/executor --dockerfile=Dockerfile --context=dir://. --destination=${QUAY_REGISTRY}/tsalawu0/buildkite-test:1.0
    artifacts:
      - /workspace/.docker/config.json  # Optionally store the config for debugging
