steps:
  - label: "Run on default Agent "
    key: delay
    commands: 
      - echo Running on default queue
      - sleep 30

  - label: "Run on queue1 Agent"
    depends_on: delay
    command: "echo Running on queue1"
    agents:
      queue: "queue1"

  - label: "Run on queue2 Agent"
    command: "echo Running on queue2"
    agents:
      queue: "queue2"

  - label: "Run on oc-image Agent"
    commands: 
      - echo Running on ocimage
      - oc whoami
    agents:
      queue: "oc-image"
